// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBBpFEm7eoJt6fhbgjtFxtfGsvPnCDOnI',
    appId: '1:13938696233:web:d1495547e5e26ce93ffc38',
    messagingSenderId: '13938696233',
    projectId: 'freezstocker',
    authDomain: 'freezstocker.firebaseapp.com',
    storageBucket: 'freezstocker.appspot.com',
    measurementId: 'G-7LVGZXQ6PR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAL8dEHZ35IZBpTnMwlue3pEZ_0sEEMYLU',
    appId: '1:13938696233:android:4ad940e23437c4c93ffc38',
    messagingSenderId: '13938696233',
    projectId: 'freezstocker',
    storageBucket: 'freezstocker.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-uRnqyDfY-8vQ9d4_XPNYjk-rnl5Z8YQ',
    appId: '1:13938696233:ios:48b62962e69154453ffc38',
    messagingSenderId: '13938696233',
    projectId: 'freezstocker',
    storageBucket: 'freezstocker.appspot.com',
    iosClientId: '13938696233-lq5h5bk2jr98fsfld7jigortp2gnfhcd.apps.googleusercontent.com',
    iosBundleId: 'com.koukilab.freezstock',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-uRnqyDfY-8vQ9d4_XPNYjk-rnl5Z8YQ',
    appId: '1:13938696233:ios:5356044a98de91003ffc38',
    messagingSenderId: '13938696233',
    projectId: 'freezstocker',
    storageBucket: 'freezstocker.appspot.com',
    iosClientId: '13938696233-pslv89cn8akb2nimuti6kiju3a1nh531.apps.googleusercontent.com',
    iosBundleId: 'com.example.freezstock',
  );
}
